language: ruby
rvm:
  - 1.9.3
  - 2.1.5
  - 2.2.2
  - 2.2.3
  - 2.2.5
  - 2.3.1
  - 2.4.1
  - 2.5.7
  - 2.6.5
  - 2.7.0
before_install:
  - git submodule update --init
  - sudo apt-get update
  - gem list
